### ISSUE TITLE
Publis HariSekhon/lib to CPAN

### ISSUE THREAD

**Issue by raags** [HariSekhon/nagios-plugins#112]
This would make it easier to install plugins on target nodes, as all dependencies can be managed with CPAN

**Comment by HariSekhon** [comment]
I had considered this a while before you raised this issue and was going to start with pylib but decided against it in the end due to the hosting terms and conditions of PyPI. It will never be possible to install everything from CPAN or PyPI anyway, so some project build / copying of the directory will be required in many cases so it's not something I can foresee solving in the near term. Future code is going to be written in other languages anyway, so they will have their own dependency management as well. In addition to this some plugins utilize the code from other adjacent plugins for code re-use, so I'm not kidding when I state in the README it's really just best to copy the whole directory as a project. Similarly in other software projects you wouldn't try to cherry pick certain parts of the directory tree as you'd  bundled libs etc, you'd copy the whole directory. This is also a result of the amount of work this project has become that it's not as simple as the usual rudimentary shell scripts etc that are found on nagios exchange.
