### ISSUE TITLE
issue while running ./check_solr_write.pl

### ISSUE THREAD

**Issue by rajesh054** [HariSekhon/nagios-plugins#152]
Can't locate Math/Round.pm in @INC (@INC contains: lib/HariSekhon/.. ./lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at lib/HariSekhon/Solr.pm line 24.

**Comment by HariSekhon** [comment]
I'd bet this is the same issue as you're having in ticket #150.

What is the result of
```
umask
```

If it says something like 0077 then it means when you installed the libraries as part of the build your environment made them only readable to root but I'd suspect you're running the nagios plugins as a regular user who cannot read the installed library files as a result.

**Comment by rajesh054** [comment]
umask is
0022

**Comment by rajesh054** [comment]
hi hari some how i have eleminated the above error for math/Round error
i want to know what parameters and argumenst shoud be configured with
./check commands for all solr , cassandra , redis ,kafka , elasticsearch plugins can u  share the syntax for the same 
please share it as early as possible 

and still i am unable to solve the problem 'can't locate kafka.pm' for check_kafka.pl

**Comment by HariSekhon** [comment]
This is an environment rather than a code issue, perhaps you changed the permissions on the library installation directories or are now running the plugin as root which had permissions.

Either way I'll close this ticket as it's not really valid.

see `--help` for each plugin, it should give you all the description necessary, then play with the switches to get the results you want.
