### ISSUE TITLE
New issue ./check_redis_slave.pl 

### ISSUE THREAD

**Issue by rajesh054** [HariSekhon/nagios-plugins#153]
CRITICAL: Can't locate Redis.pm in @INC (@INC contains: lib/HariSekhon/.. ./lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at lib/HariSekhon/Redis.pm line 24.

When tried finding  the location of the Redis.pm  then it  is showing some other location 
so i have tried copying the file from that location to the required location
this resolves the issue but then asks for other dependencie 
how can i fix this , same is the case for check_kafka.pl please help

**Comment by HariSekhon** [comment]
Rajesh, this is an environment problem, not a code issue with this project.

You simply have to make sure the library directories are chmod -R 755 so that the user you're running the plugins can access them or check your $PERLPATH have included the directory tree where the libraries are installed.

If you want to have a thread on this please stop opening new tickets for it each time and use the one ticket to track your environment issue.
