### ISSUE TITLE
check_ssl_cert.pl and openssl 1.1

### ISSUE THREAD

**Issue by ManicoW** [HariSekhon/nagios-plugins#163]
Hello,

While updating my monitoring to debian stretch, I encountered two problems with check_ssl_cert.pl

1/ CApath

The CApath determined from openssl is not correct anymore. After some debug, it appears that the CApath determined from openssl 1.0 and 1.1 is the same (/usr/lib/ssl/ here), but using this CApath with openssl 1.1 does not permit to validate certificates. I think that the CApath was used recursively by openssl 1.0 but not by openssl 1.1, but I don't find any information validating this. 

"Solved" by using the -C option to specify a correct CApath (/usr/lib/ssl/certs/ here)

2/ Subject of the certificate

openssl 1.1 don't show the subject of the certificate the same way that openssl 1.0 did, it is now
"Subject: CN = backupint01.wdmedia-hebergement.net" with spaces arround the equal sign.

Solved by adding \s* arround the equal sign in the regexp for subject

Regards,

**Comment by HariSekhon** [comment]
Hi @ManicoW 

Thanks very much for raising this issue, I'm merged in your patch for the certificate subject update.

I've checked on the CApath issue and indeed you are correct OpenSSL 1.1 behaviour appears to have changed, so I've done a patch to make it work by leaving it to use the default ca path rather than trying to infer the ca path from the openssl binary itself which is sort of lying now.

I've tested this on Debian Stretch and it works. You can also run `tests/test_ssl_cert.sh` to validate yourself (I've just split this off from `tests/test_unix.sh` to make this easier to test by itself as this is such a popular plugin).

Thanks

Hari

**Comment by Twibow** [comment]
Hello @ll,

I've already an issue on check_ssl_cert.pl on CentOS release 6.9 (Final).

The CA trust is merged on on bundle file : 
[maintenance@CENTREON harisekhon-collection]# ll /etc/ssl/certs/
total 1916
-rw-r--r-- 1 root root  884985 May  9  2017 ca-bundle.crt
-rw-r--r-- 1 root root 1058960 May  9  2017 ca-bundle.trust.crt
-rwxr-xr-x 1 root root     610 Mar 22  2017 make-dummy-cert
-rw-r--r-- 1 root root    2242 Mar 22  2017 Makefile
-rwxr-xr-x 1 root root     829 Mar 22  2017 renew-dummy-cert

SO I obtain the famous error : "CRITICAL: Certificate validation failed, returned 19 (self signed certificate in certificate chain)"

Have you a alternative for my issue ?

**Comment by HariSekhon** [comment]
@Twibow 

I missed this as this is a closed ticket, would have been better to raise a new issue one...

Did you try to use the option  `--CApath /etc/ssl/certs/`? (I can't tell as you didn't paste the command and full output)

Can you please paste the full output when using  `-v -v -v` (you can use scrub.pl from my [Tools](https://github.com/harisekhon/tools) if you want to anonymize internal hostnames / IPs etc)
