### ISSUE TITLE
Nagios-Opsview Exec Error

### ISSUE THREAD

**Issue by ljcastro** [HariSekhon/nagios-plugins#181]
Hi everyone,

I have problems running the plugins in Opsview. I've created a service check for logstash, and everything runs OK from command line, as well as from "troubleshoot" option in Opsview.

But when the system tries to automatically run the check, it fails with a 126 error: "(Return code of 126 is out of bounds - plugin may not be executable)"

It seems to be a permissions issue, or something else...

Anybody knows something about this issue?

Thanks in advance!

**Comment by HariSekhon** [comment]
That returncode is happening before the plugin is executed and seems to be caused by a mode error.

I suspect you've tested execution as root or another user who has octal permissions to the plugin but the user running opsview doesn't.

Check permissions are executable for the user running the check, 0755 to simplify, and don't forget to check each directory in the path to the plugin as well. You should also ensure the adjacent pylib directory and its contents are also readable by the user.

**Comment by ljcastro** [comment]
Thanks HariSekhon,

I'm using the docker image in order to run the plugins, maybe would that be the problem? As far as I know, permissions in container plugins are 755.

I can execute the plugins with the user "nagios" without errors in the shell, and this is the user who is running all of our service checks.

**Comment by HariSekhon** [comment]
Are you leaving interactive switches like `-t` or `-i` when OpsView is running without an interactive user shell?

If so try removing those options to the docker run command.

**Comment by HariSekhon** [comment]
Closing for lack of feedback.
