### ISSUE TITLE
nodetool not found in docker image

### ISSUE THREAD

**Issue by jazzl0ver** [HariSekhon/nagios-plugins#183]
Hi and thanks for such auseful bunch of tools!
I'd like to utilize the docker option for calling the tools. Unfortunately, when calling Cassandra tools, it does not find nodetool (and no java as well):
```
/bin/docker run --rm harisekhon/nagios-plugins check_cassandra_nodes.pl
UNKNOWN: couldn't find 'nodetool' in $PATH (/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/local/cassandra/bin:/opt/cassandra/bin:/cassandra/bin)
```
Please, advise!

PS Calling the docker on Amazon Linux 2 EC2 instance.

**Comment by HariSekhon** [comment]
Good question - you would actually need to use the `harisekhon/cassandra-dev` image instead to have nodetool available for that and similar cassandra plugins.

**Comment by jazzl0ver** [comment]
Thanks for such a fast reply!
Could you please shed some light on the usage? Looks like harisekhon/cassandra-dev does not have check_cassandra_nodes.pl script..

**Comment by HariSekhon** [comment]
It is there as that image is based off the nagios-plugins:alpine image (you can see the Dockerfile https://github.com/HariSekhon/Dockerfiles/blob/master/cassandra-dev/Dockerfile linked from the Dockerhub repo https://hub.docker.com/r/harisekhon/cassandra-dev/).

It is used for the tests in this repo but it defaults to running cassandra and then docker exec's run the plugins. out of the long running container, which is why you're not seeing it.

I've just pushed a fix which states if you provide arguments then it won't run cassandra, try:

```
docker run harisekhon/cassandra-dev check_cassanode_netstats.pl -h
```

**Comment by jazzl0ver** [comment]
Thank you very much!

**Comment by jazzl0ver** [comment]
Sorry for re-opening. Just found this:
```
# /bin/docker run --rm harisekhon/cassandra-dev check_cassanode_netstats.pl -h
container_linux.go:262: starting container process caused "exec: \"check_cassanode_netstats.pl\": executable file not found in $PATH"
/bin/docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"check_cassanode_netstats.pl\": executable file not found in $PATH".
ERRO[0000] error waiting for container: context canceled
```

**Comment by jazzl0ver** [comment]
Looks like it's just a typo - check_cassandra_netstats.pl works well.
