### ISSUE TITLE
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade 

### ISSUE THREAD

**Issue by pantoufleCC** [HariSekhon/Nagios-Plugins#225]
What are options about python and this warning ?
Does my favorite container used by nagios will still work next year ? :-D

as i'm not a developper, i don't know if i need to take care about this message or not ?

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

regards,

**Comment by HariSekhon** [comment]
The docker container will continue to work regardless of this as it is built and saved and if the build breaks it won't replace the existing latest docker image.

The Python 2 vs 3 situation was a mistake by the developers and is a horrible situation for everyone but will manage it as we go forward.

I already did most of the Python code rewrites to be compatible with Python 3 a very long time ago, so even if you wanted to move to Python 3 (most OS and production systems still haven't moved to Python 3) then it should already work, maybe need the odd new module install since some modules have gone from `<name>` to `<name>3` since it was such a big breaking change for them. I didn't enable CI builds on Python 3 because at the time not all of the library dependencies supported it, but will put this back on the todo list.

Right now docker image usage insulates you from this issue, and also since most production servers RHEL/CentOS/Debian/Ubuntu are still on Python 2 even straight builds will still work the same.
