### ISSUE TITLE
Cloudera plugin is working, but we need to run the script with user and password variables 

### ISSUE THREAD

**Issue by chandanbalaji121986** [HariSekhon/Nagios-Plugins#243]
Hello Hari,

Cloudera plugin is working and thank you so much for that :) But **we need to run the script with test user and test password variables within a file as we are not suppose to specify actual username and password in command prompt**.... this is for nagios monitoring.....

**./check_cloudera_manager_license.pl -H <hostname> -P XXXX -u test -p test123 -A --tls-noverify*

**Comment by HariSekhon** [comment]
You can put `$CM_USERNAME` and `$CM_PASSWORD` environment variables so that the username and password are not on the command line or shown in the process list. Those credentials can be loaded in to the environment using the `read -s CM_USERNAME` and `read -s CM_PASSWORD` commands.

Alternatively, newer versions of Cloudera Manager support SPnego Kerberos authentication.

https://docs.cloudera.com/documentation/enterprise/latest/topics/cm_intro_api.html

If you `kinit` with a valid user account then the plugin should be able to pick up kerberos TGR credentials from the environment as long as LWP::Authen::Negotiate is installed.

**Comment by chandanbalaji121986** [comment]
your response is highly appreciated and thank you for that. I am not that familiar with cloudera manager and its functionality. I am nagios admin and I need onboard CM servers and its respective services in nagios.... when we tried your scripts it was fitting 100% to our request, hence is there any where we can change in the script level itself ?!!

**Comment by HariSekhon** [comment]
You mean embed the username and password in the script?? I wouldn't recommend it but you could do it by replacing these 2 lines with static settings:

```
$user       = validate_user($user);
$password   = validate_password($password);
```

https://github.com/HariSekhon/Nagios-Plugins/blob/master/check_cloudera_manager_license.pl#L55-L56

Ultimately though the reason I support environment variables is so that you don't have to do things like that. If you want to put `--username` and `--password` you can do that, if you want to try kerberos via `kinit` or if you want to use the environment variables stored externally to the script (in nagios or environment), then you can do that too. Those are all the possible options I can think of.

**Comment by chandanbalaji121986** [comment]
Thank you so much Hari, it worked :)

**Comment by HariSekhon** [comment]
You're welcome :)

**Comment by chandanbalaji121986** [comment]
Hello Hari,

Do you have any Perl script for network bandwidth usage for VMWARE and
physical machine ??
If you have any kindly let me know...

Regards,
Chandan Balaji A S

**Comment by HariSekhon** [comment]
No I don't work with VMware any more and I didn't get round to recreating the sorts of plugins we used to use back in the day...

You might want to check Nagios Exchange as there are pages of vmware plugins:

https://exchange.nagios.org/index.php?option=com_mtree&task=search&Itemid=74&searchword=vmware

**Comment by chandanbalaji121986** [comment]
Thank you Hari for all your responses ..
