### ISSUE TITLE
check_hdfs_space not working after Cloudera update

### ISSUE THREAD

**Issue by marbaa** [HariSekhon/Nagios-Plugins#254]
Hello,

after Cloudera update from 5.15 to 6.3 check_hdfs_space stopped working.
![image](https://user-images.githubusercontent.com/40859847/71884046-daadb180-3137-11ea-977d-0c8124dcca16.png)

Default port for this service was changed by Cloudera from 50070 to 9870. I tried to change the port in few scripts, but didn't helped.
![image](https://user-images.githubusercontent.com/40859847/71884245-3841fe00-3138-11ea-95f3-fe432d7553ba.png)

Looks like they've changed more than just default port.

**Comment by marbaa** [comment]
Attached is script executed with -vvv.
[output.zip](https://github.com/HariSekhon/Nagios-Plugins/files/4030083/output.zip)

**Comment by HariSekhon** [comment]
Thanks for sending the full output, I've done an update in the hadoop-3.x branch.

Please try the version from

https://raw.githubusercontent.com/HariSekhon/Nagios-Plugins/hadoop-3.x/check_hadoop_hdfs_space.pl

**Comment by marbaa** [comment]
Thank you for prompt reaction. But that didn't help. I see you commented the port 9870 and uncommented port 50070:

#set_port_default(9870);
set_port_default(50070);

Port 50070 is not used anymore. Now it is listening on 9870. If I change the port to 9870, then there is issue with output - 'FilesTotal' field not found. API may have changed. As on screenshot.

**Comment by HariSekhon** [comment]
Ok the reason for that is the FilesTotal field is in a different mbean. I have pushed another update to the hadoop 3.x branch which uses a different mbean query now.

Please try the latest 0.4.0 version in the hadoop-3.x branch found here:

https://raw.githubusercontent.com/HariSekhon/Nagios-Plugins/hadoop-3.x/check_hadoop_hdfs_space.pl

and let me know.

I've not changed the default port because I don't want to break existing deployments.

Thanks

Hari

**Comment by marbaa** [comment]
Understand that with not changing the default port.
Tried newest version, checks works now!

Thank you very much for real fast fix.
Marek

**Comment by HariSekhon** [comment]
I've back tested it and merged to master now.

Thanks for raising this.

Cheers

Hari
