### ISSUE TITLE
check_updates reports security updates needed incorrectly

### ISSUE THREAD

**Issue by philrumble** [HariSekhon/Nagios-Plugins#296]
check_update reports security updates needed when , in fact none are needed.

/usr/lib64/nagios/plugins/check_updates --clean -w 75 -c 150 -t 30 -vvv
[extra-opts] check_updates --clean -w 75 -c 150 -t 30 -vvv
Searching for DNF or YUM in /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
Executing 'which dnf'
which: no dnf in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
Executing 'which yum'
/usr/bin/yum
Checking a linux system
Running on CentOS Linux release 7.7.1908 (Core)
Using Yum or DNF
running a Linux kernel: 3.10.0-1062.12.1
kernel: running = 3.10.0-1062.12.1, installed = 3.10.0-1062.12.1
Checking if YUM/DNF supports the --security option
Using YUM: security plugin installed
Cleaning YUM/DNF cachesSecurity updates available
CHECK_UPDATES CRITICAL - 2 security updates and 1 non-security update available | total_updates=3;75;150 security_updates=2;75;150
Repository (security)
Repository (security)
python-urllib3.noarch

using yum
sudo yum check-updates --security --quiet
Repository extras is listed more than once in the configuration
Repository updates is listed more than once in the configuration

**Comment by HariSekhon** [comment]
That's looks like a forked version as I haven't done an update for dnf yet and am intending on writing a whole new plugin for it.

If you can download the version from this repo and paste the full -vvv output then I'll have a go at debugging and patching if necessary. I cannot reproduce or patch if you are using some forked version to which I don't have the original code.

**Comment by HariSekhon** [comment]
This was on the backlog since #226 waiting for CentOS to release a version 8 docker image to develop against. Since CentOS 8 docker images are now available so I've pushed a compatibility update, please try the latest version from this repo and let me know.

I do not have any system in need of security updates, so cannot test that part until DNF systems actually get some security updates which I can test via docker.

**Comment by philrumble** [comment]
This was found on centos7

**Comment by HariSekhon** [comment]
That's a completely different piece of code written by a different author.

If you open the file with an editor you can see the author in the comments near the top:

```
$ grep Copyright /usr/lib64/nagios/plugins/check_updates                                                                                                                             
# Copyright (c) 2007-2019 Matteo Corti <matteo@corti.li>
```

You're welcome to download `check_yum.py` from here and try that instead, otherwise you'd need to contact that email address instead.
