### ISSUE TITLE
can't make fatpacks after make for check_redis_*

### ISSUE THREAD

**Issue by dada216** [HariSekhon/Nagios-Plugins#327]
the system is a rhel8, I used the automatic build and all went fine, I now need to distribute some of these plugins to other machines for execution without the need to recompile the whole thing, the make fatpacks function is an amazing idea, I can't get it to work tho.

those redis_check plugins do need libraries and are not distributable as is to other machines.

```
[root@hostname]# make fatpacks check_redis_*
bash-tools/perl_generate_fatpacks.sh *.pl
================================================================================
                            FatPacking Perl Scripts
================================================================================

Generating App::FatPacker self-contained perl scripts with all dependencies:


Generated 0 fatpacked scripts under fatpacks/ directory

'lib/resources/custom_tlds.txt' -> 'fatpacks/resources/custom_tlds.txt'
'lib/resources/tlds-alpha-by-domain.txt' -> 'fatpacks/resources/tlds-alpha-by-domain.txt'

make: Nothing to be done for 'check_redis_clients.pl'.
make: Nothing to be done for 'check_redis_config.pl'.
make: Nothing to be done for 'check_redis_key.pl'.
make: Nothing to be done for 'check_redis_publish_subscribe.pl'.
make: Nothing to be done for 'check_redis_replication.pl'.
make: Nothing to be done for 'check_redis_slave.pl'.
make: Nothing to be done for 'check_redis_stats.pl'.
make: Nothing to be done for 'check_redis_version.pl'.
make: Nothing to be done for 'check_redis_write.pl'.
make: Nothing to be done for 'check_redis_write_replication.pl'.
```

**Comment by HariSekhon** [comment]
The commands is just:

```
make fatpacks
```

which will generate a `fatpacks` directory full of scripts with their libraries copied in to them, and tar it so you can just scp and untar on the remote servers.

The scripts do still need the fatpacks/resources text files with valid IANA TLDs for validations, which is why it's done as a directory and not as a single script. The Make command handles all of this for you, but I've left the call to fatpacking script it uses underneath as visible in case you wanted to call it directly:

```
bash-tools/perl_generate_fatpacks.sh *.pl
```

The reason you are getting those `Nothing to be done for` errors way you have appended `check_redis_*` has passed as arguments the names of all the redis checks to the `make` command which is saying there are no Make configurations for those names.

I've also just realized a small bug was introduced in to the fatpacks script in the submodule as indicated by the zero counter of fatpacked scripts which is not correct. I've just pushed a fix, please `make update2` to pull the submodule and then try:

```
make fatpacks
```

alternatively you could run it for just the redis scripts you could alternatively run manually:

```
make update2 # to get the latest bash-tools submodule with the fatpack script

bash-tools/perl_generate_fatpacks.sh check_redis_*.pl

cp -av lib/resources fatpacks/
```

Then tar/scp the directory around as you wish with the dependencies self-contained.

In general I tend to do everything as a group as it's simpler, so you may want to just stick to `make update2 fatpacks` and then just use the tarball generated for you.

**Comment by dada216** [comment]
thank you very much, I actually did tried to run `make fatpacks ` without arguments but I was getting 
`
Generated 0 fatpacked scripts under fatpacks/ directory`

and that's why I thought I needed to provide it a name, your explanation was very clear and after `make update2 `rerunning `make fatpack` generated the scripts correctly.

**Comment by HariSekhon** [comment]
Thanks for confirming.
