### ISSUE TITLE
Would it be possible to add into check_file_checksum.pl to verify http/https downloaded files?

### ISSUE THREAD

**Issue by elicro-rimon** [HariSekhon/Nagios-Plugins#351]
I need to monitor a small file change on a server, maybe such a function can be added?
For my scenario I have the md5 checksum of the file and I need to verify if it's the same or not.
Additional data might be the current downloaded file size and md5 checksum.

Would it be possible to add this feature?

**Comment by HariSekhon** [comment]
It would probably be better done as a separate type of check, a network http/https check instead of a local file check.

The reason is that doing one thing well is the best way to write code and follows battle tested unix philosophy which has been proven over several decades.

I don't really have a use case for this check or the time to write it right now, but will leave this on the backlog as a feature request.

If you want to implement this yourself, you could wrap this in a simple shell script like this if the md5 checksum file is in the right format:

```
#!/usr/bin/env bash
#  vim:ts=4:sts=4:sw=4:et
#
#  Author: Hari Sekhon
#  Date: 2020-10-27 23:45:10 +0000 (Tue, 27 Oct 2020)
#

set -euo pipefail

wget -O "filename.txt" https://www.domain.com/filename.txt
wget -O "filename.md5" https://www.domain.com/filename.md5
md5sum -c filename.md5
```

or if the file only contains the checksum, or you want to extract it and still use the checksum plugin, then:

```
#!/usr/bin/env bash
#  vim:ts=4:sts=4:sw=4:et
#
#  Author: Hari Sekhon
#  Date: 2020-10-27 23:45:10 +0000 (Tue, 27 Oct 2020)
#

set -euo pipefail

wget -O "filename.txt" https://www.domain.com/filename.txt
wget -O "filename.md5" https://www.domain.com/filename.md5

# pick one of the two next lines - the first if the file only contains the checksum, the second if the checksum is in standard .m5d format with the checksum in the first field
#checksum="$(cat filename.md5)"
checksum="$(awk '{print $1; exit}' filename.md5)"

check_file_md5.pl -f filename.txt -c "$(cat filename.md5)"
```

The `set -e` and `set -o pipefail` behaviours mean you'll still get error codes if anything goes wrong in the check.

**Comment by elicro-rimon** [comment]
@HariSekhon Thanks, I was thinking to write a bash or ruby script.
I will try to sit on this later on today to meet my requirements.

**Comment by elicro-rimon** [comment]
@HariSekhon I wrote a helper which might be good for some cases:
* <https://github.com/elico/check-url-md5>
