### ISSUE TITLE
check_redis_stats.pl doesnt return useful perfdata on all metrics

### ISSUE THREAD

**Issue by vColonel** [harisekhon/nagios-plugins#38]
Using check_redis_stats.pl for items including memory used and peak memory used returns the query time in milliseconds but not the actual memory used in MB:

$ check_redis_stats.pl -H 'x.x.x.x' -s used_memory_human
RETURN CODE: 0 (OK)
OUTPUT:
 OK: used_memory_human=110.67M, queried server in 0.00091 secs | query_time=0.00091s

**Comment by harisekhon** [comment]
It's designed for ```used_memory``` not ```used_memory_human``` for perfdata

I've just code extra logic to enable perfdata and threshold checking for human stats if you specify them explicitly with the ```-s/-stats``` switch as you are doing which should solve your requirement. In default mode when just listing all stats it still won't output the human stats since it's redundant information because each stat has the normal version (which is more accurate there is a rounding error having to multiple out human stats), you can specify the stats explicitly if you want that. This should satify all use cases.

Please git pull and try the latest version it should resolve this ticket. Please re-open if it does not or you encounter any related issue.

Best Regards,

Hari

**Comment by vColonel** [comment]
Hi Hari,

Works a charm! I'm splitting them out into seperate service checks so this works a treat.

Cheers,
Sam
