### ISSUE TITLE
check_yum plugin shows 0 non-security updates

### ISSUE THREAD

**Issue by ChaouchKarim** [HariSekhon/Nagios-Plugins#384]
Hello folks,

The `check_yum` plugin shows `0 Non-Security Updates Available` even though there are hundreds of non-security updates.
I don't know if this was intentional but in the script `num_total_updates = 0` and that's why I have 0 non-security updates in the output.
To have the desired output, I simply changed the script as following:

```epp
431       if not summary_line_found:
432            if os.path.exists(DNF) and re.match('Last metadata expiration check: ', ''.join(output)):
433                using_dnf = True
434               num_total_updates = self.get_all_updates() #line changed
```
...
```epp
495        num_other_updates = num_total_updates - num_security_updates
```
Could you please explain why I have 0 updates with your script ?
Cheers,
Karim

**Comment by HariSekhon** [comment]
Thanks for raising this, could you please paste the full output with `-v -v -v` so that I can debug your exact situation and find out why it's not picking up the non-security updates any more.

It's likely that updates to cover newer releases has broken this recently as this has been known working for many years, or it's possible that the output format has changed.

**Comment by HariSekhon** [comment]
Are you running both the plugin and the `dnf check-update` commands as root?

You may get different results if you use a non-root user...

The output in the plugin and from `dnf check-update` should be the same.

**Comment by ChaouchKarim** [comment]
Thank you for the information @HariSekhon.
I'm currently running both checks as suggested.
