### ISSUE TITLE
check_hadoop_hdfs_file_webhdfs.pl crash

### ISSUE THREAD

**Issue by fuqqer** [harisekhon/nagios-plugins#48]
When executing from the command line of a nagios server, the command works:
/usr/lib/nagios/plugins/check_hadoop_hdfs_file_webhdfs.pl -H myhostaddress -p "/path/to/myfile" -m somenumber -v

When executing from within nagios I get the following error:
Use of uninitialized value $user in concatenation (.) or string at /usr/lib/nagios/plugins/check_hadoop_hdfs_file_webhdfs.pl line 161.
CRITICAL: 500 userName is NULL, empty or contains a '&'

Also, the plugin does not check if a name node is primary before checking the file status.  Checking file status against a secondary node will always fail.  It would be nice if the check did a pre-flight check for a primary.
If no primary is found, it should return critical because nothing can be read from.
If a primary is found, that should be used to list the file properties.

**Comment by harisekhon** [comment]
@fuqqer

I've tweaked this program to re-enable an extra method to try to determine your user and added a check on it before sending to NameNode.

Please git pull and try again and paste back the -vvv output if still having issues.

Regarding the second point of determining the primary NameNode, this would require extra logic and extra network round trips (that's what the HDFS client libraries do) and is what HttpFS server is designed to abstract for all WebHDFS API programs.

This may not be obvious to all but for a a NameNode HA setup you shouldn't be pointing this program at a NameNode directly but should instead be going via the HttpFS server which you need for other components anyway. I'd added a note to the program usage description about this.

Regards,

Hari

**Comment by harisekhon** [comment]
@fuqqer 

Any feedback on the above or should I close this ticket?

**Comment by harisekhon** [comment]
It's been nearly 2 weeks, closing.

**Comment by fuqqer** [comment]
I'm confused...
I'm not using httpfs and don't use it on my hdfs installation.  I'm using webhdfs.

In the usage output, check_hadoop_hdfs_webhdfs.pl says the -H flag is meant to check on a name node.

Output from checking file status on a standby node:
$ ./check_hadoop_hdfs_webhdfs.pl -H namenode2 -p /pathtomyfile -m 100
CRITICAL: 403 Forbidden: org.apache.hadoop.ipc.StandbyException: Operation category READ is not supported in state standby

Output from checking file status on an active node:
./check_hadoop_hdfs_webhdfs.pl -H  namenode1 -p /pathtomyfile -m 100
OK: '/pathtomyfile' exists type=FILE owner=myuser group=mygroup permission=644 blockSize=134217728 replication=3 size=15 accessTime=1430939014 modifiedTime=1430939015

Maybe I'm missing something in how to use the plugin?  It's implied that the plugin checks a file via webhdfs on a name node.  Name nodes are meant to be in active/standby state and querying a standby doesn't work.

**Comment by fuqqer** [comment]
The other bug about no name available is fixed!  Thanks for that and thanks for all the plugins!

**Comment by harisekhon** [comment]
@fuqqer 

HttpFS is the same protocol as WebHDFS - if you're using HDFS HA you're supposed to use HttpFS as the proxy to handle the failover since otherwise clients such as Hue will break when NN fails over.

I've just added HDFS HA support directly in this plugin to do the same behaviour as the original HDFS java client - you can specify multiple NameNodes comma separated for --host and it will try each one in succession. This is how the official client for MapReduce does it. The downside with this approach over HttpFS is that it's 2 round trips, which increases the plugin run time and you're more likely to hit timeouts.

If you run with -vv you can see it fail over if you specify --host standbyNN,activeNN  (the order is preserved, it will try them in the order given).

Anyway, enjoy the new HDFS HA direct support!
