### ISSUE TITLE
check_ambari_services.pl Kerberos=STOPPED is o.k.

### ISSUE THREAD

**Issue by fnerdwq** [harisekhon/nagios-plugins#50]
Hello,

in Ambari 2.0.0 the Kerbers an be managed. This is shown by Ambari as a Service in the state STOPPED, which is `ok`, but handles as `critical` by the check. 

Output by an Kerberized Cluster
```
CRITICAL: Ambari services: Flume=started, Ganglia=started, HBase=started, HDFS=started, Hive=started, Kerberos=STOPPED, MapReduce2=started, Oozie=started, Pig=installed, Slider=installed, Sqoop=installed, Tez=installed, Yarn=started, ZooKeeper=started
```

Bye
Frederik

**Comment by harisekhon** [comment]
Ah yes Ambari has added yet another component that doesn't have a 'running' state.

I've added this to the list of components to report but not expect running or raise critical on since they don't have running states, and mentioned this in the usage help that it's easy to extend this as there is a list at the top of the code (but please submit a patch or raise a ticket to let us know if you add to the list of non-running services).

Regards,

Hari
