### ISSUE TITLE
check_mysql_query.pl - No output on stdout on timeout

### ISSUE THREAD

**Issue by debiasi** [harisekhon/nagios-plugins#54]
I was using check_mysql_query that came with nagios plugins and when I get a query timeout (because other query is locking tables) I received the message: Service check timed out after 60.02 seconds) and CRITICAL to Nagios.

Using check_mysql_query.pl in the same situation I get no message when I run the script on shell and on Nagios I get "(No output on stdout) stderr:" message with an OK on Nagios.

Is there a way to this perl script consider timeout as an error or warning ?

**Comment by debiasi** [comment]
I tried to run in another period of the day when the DB is without too many connections and without locking tables and I get the same situation.

My query is SELECT IFNULL((SELECT ROUND(count(fpr_id)/count(distinct(numero_maquina))) as total FROM fila_processamento WHERE nome_fila = 'publicacao' AND status = 'pendente'),0) as total

**Comment by harisekhon** [comment]
All the Perl plugins come with native --timeout support returning UNKNOWN as well as trapping the die handler for any unforeseen problems to return CRITICAL, as well as redirecting all output to stdout since Nagios doesn't catch stderr.

If your query is taking a long time such that the plugin is waiting on MySQL for the results to the query and Nagios kills the plugin after the global service check timeout before the plugin has received the query to to print anything then that may be why you get this (null) output which Nagios prints when it didn't receive any stdout from the plugin before killing it.

I would guess that you've reset the plugin's --timeout to something >= higher than that of the Nagios service check global timeout but even then Nagios itself is supposed to give you an UNKNOWN is it times out a plugin, not OK. It's better to have the plugin self-timeout itself which is why the program comes with --timeout support natively. If you were to use that, the plugin itself will print something out as well as returning UNKNOWN, instead of leaving it to Nagios. This is good practice to set --timeout sensibly.

Can you please execute the query again on the command line with ```-v -v -v``` to get more debugging output and paste the full output back in to this ticket?

**Comment by debiasi** [comment]
I am running this check with low load database and no lock queries:

shell> command
check_mysql_query.pl version 1.1.1  =>  Hari Sekhon Utils version 1.11.2

host:                     1.2.3.4
port:                     3306
user:                     nagios
password:                 <omitted>
database:                 mydb
query:                    SELECT IFNULL((SELECT ROUND(count(fpr_id)/count(distinct(numero_maquina))) as total FROM fila_processamento WHERE nome_fila = 'publicacao' AND status = 'pendente'),0) as total
field:                    1
warning  lower:           0
warning  upper:           399
critical upper:           600
setting timeout to 60 secs

connecting to MySQL database on '1.2.3.4:3306' as 'nagios'
login to database successful
shell>

**Comment by harisekhon** [comment]
@debiasi 

Questions:

1. Does it work for other queries, is it only this query or all queries that you have a problem with?

2. Did it work before and then stop working or did it never work?

3. Have you run a ```make update``` and then try again since I noticed you're using an older version of the library (mine is 1.12.9 vs your 1.11.2).

I've just run the latest version and it's fine, I've just run it to list tables on information schema as a quick test:
```
...
login to database successful

query: show tables in information_schema
query executed in 0.0010 secs
result row:  CHARACTER_SETS
result: CHARACTER_SETS

OK: query returned 'CHARACTER_SETS' | mysql_query_time=0.0010s
```

**Comment by harisekhon** [comment]
@debiasi 

Any feedback on this?

**Comment by debiasi** [comment]
Yes. 

1.    All queries are not working.

2.  I tested before and it worked, but I did not put in production. When I was going to put it I receive the error.

3. I just update the plugins and it worked but:

A) Utils keeps the same version 
check_mysql_query.pl version 1.1.1  =>  Hari Sekhon Utils version 1.11.2

B) When I do the make update it updates the Utils too ?

And I get an error on 2 queries:

ERROR: invalid query defined: may only be a SELECT or SHOW statement

queries:

SELECT count(distinct(pro_id)) FROM workflow  JOIN produto ON wkf_pro_id = pro_id AND pro_delete = 1 JOIN produto_os ON pro_id = por_pro_id AND por_delete = 1 WHERE wkf_stw_id = 44 AND wkf_delete = 1

SELECT count(distinct(sku_os)) as total FROM processamento_audit WHERE status = 'erro' AND delete = 1

**Comment by harisekhon** [comment]
@debiasi 

When updating you must run ```make update``` otherwise you have to do ```git submodule update``` by hand (you should try ```git submodule update``` anyway to get the latest library in case it didn't work and you missed it in the larger output before).

Those 2 queries are blocked by design as the plugin looks for words like "delete" and refuses to run for safety. I'm open to refining this while maintaining enough safety. If you update the library then you can find the lines that check this at 3020 and 3021 in lib/HariSekhonUtils.pm to have a look.

**Comment by debiasi** [comment]
I did the git submodule update and the script from nagios-plugins directory shows the new version. I copied to /usr/local/nagios/libexec but it show the old one. I don't remember what I did to install your utils :/

**Comment by harisekhon** [comment]
@debiasi 

Either copy the whole nagios-plugins directory as-is or you must copy the whole lib subdirectory along with the plugin. The code looks for lib/ directory in the same location as the plugin is being run from.

**Comment by debiasi** [comment]
@harisekhon 

Thanks! Now it worked. I copied the lib directory and the script shows the last version.
