### ISSUE TITLE
Missing dependencies when compiling on Debian Jessie

### ISSUE THREAD

**Issue by maticmeznar** [harisekhon/nagios-plugins#57]
While running make on your repo as per instructions on Debian Jessie (in a Docker container), I got several errors about missing files. I had to install the following packages to fix the dependency problems:

sudo git make
libexpat1-dev python python-pip libpython-dev libsnappy-dev

I recommend you add them to the list of packages that are already automatically installed so other people won't have the same problem.

**Comment by harisekhon** [comment]
@maticmeznar 

That's weird I already put those packages in the Makefile, look at the Makefile in the section ```apt-packages``` it's listed there it has:

```
... apt-get install -y libexpat1-dev ...
....
... apt-get install -y python-setuptools python-dev libev4 libev-dev libsnappy-dev ...
```

**Comment by maticmeznar** [comment]
I just tried it in a Debian 8 Vagrant Box, thinking Docker's image is maybe too stripped down and is missing some essentials, however, I still had to manually install "python-setuptools python-dev libsnappy-dev".

Also, when make runs "easy_install -U setuptools" it fails, because the command requires to be run as root because it needs to write to some system folders.

On an unrelated note, Debian Jessie is missing jwhois package, while being present in squeeze, wheezy and sid.

**Comment by harisekhon** [comment]
@maticmeznar 

Ok I've changed  the ```easy_install -U setuptools``` to run as root just now if you're not already root but not sure what to do with those packages, they're clearly in the package list and this used to work on previous versions of Debian. I'd have to build a new VM and see what's up later... 

What's also interesting is has CI run on Ubuntu which shows those packages no longer exist, package names must have changed? :-/

All the plugins should work fine without this stuff since it's actually just for a Cassandra Python driver that's not used right now anyway.

The jwhois package is the only exception - ```check_whois.pl``` needs that. Is there a package replacement for it? Perhaps it's available in some optional tertiary repo now or something? Since not all people will use all plugins I'm not inclined to fail the entire build for 1 plugin dependency out of 200 that they may never use and will be told by the plugin to install jwhois if they try to run it, it's mostly for convenience to try to pull in everything. That being said if you know a workaround I'm happy to include it for everyone's future convenience.

**Comment by maticmeznar** [comment]
I resolved the jwhois problem by manually downloading and installing jwhois for Debian Wheezy from http://httpredir.debian.org/debian/pool/main/j/jwhois/jwhois_4.0-2.1_amd64.deb . It installs and works fine on Debian Jessie.

**Comment by harisekhon** [comment]
@maticmeznar 

I'm tempted to add an attempt to download and install that deb if the apt-get fails, something like

```dpkg -i http://httpredir.debian.org/debian/pool/main/j/jwhois/jwhois_4.0-2.1_amd64.deb```

and ignore if it fails.

**Comment by maticmeznar** [comment]
Yeah, I've filled a bug report with Debian about the missing package for jessie, but it's probably a long shot.

If I remove
`dpkg -l python-setuptools python-dev libev4 libev-dev libsnappy-dev &>/dev/null ||`
from Makefile and leave the second part of the line, the Makefile completes fine.

**Comment by harisekhon** [comment]
Ok I've just commented out that portion of the line so it tries to install those packages regardless - this is cheaper to do on Debian systems since the package manager is much faster, on RHEL it's annoyingly slow which is where this check or install logic came from, so it's fine to leave off in this case.

I think we should probably close this ticket and leave the jwhois issue since it'll probably fix itself after the Debian folks get round to reinstating the package.

You can re-open if needed.

**Comment by maticmeznar** [comment]
Thank you.
