### ISSUE TITLE
check_dns.pl -s parameter only accepts IP, hostname doesn't work

### ISSUE THREAD

**Issue by maticmeznar** [harisekhon/nagios-plugins#58]
`$ ./check_dns.pl -s prestreljenik.arnes.si -r arnes.si -q MX`
`DNSCRITICAL: Insecure dependency while running with -T switch at /usr/local/lib/x86_64-linux-gnu/perl/5.20.2/Net/DNS/Resolver/Base.pm line 849.`

`$ ./check_dns.pl -s 193.2.1.66 -r arnes.si -q MX`
`DNS OK: arnes.si MX record returns 'kanin.arnes.si' | dns_query_time='0.0089s'`

`$ host prestreljenik.arnes.si`
`prestreljenik.arnes.si has address 193.2.1.66`
`prestreljenik.arnes.si has IPv6 address 2001:1470:8000::66`

Perhaps change -s parameter so it requires an IP address.

This could be related to https://rt.cpan.org/Public/Bug/Display.html?id=99814

**Comment by harisekhon** [comment]
@maticmeznar

This is due to Perl security mode that I run everything through and while the input is validated perl needs to be told to untaint it. The upstream module may be failing to untaint it but I've just pushed a new version which should resolve this in the client code.

I'd rather keep the option of supplying either a hostname or an IP for the DNS server(s) for convenience, but of course the IP will always be more efficient since it's one thing to resolve.

Please try the latest version with the hostname and let me know.

Regards,

Hari

**Comment by maticmeznar** [comment]
It's working now. Thank you!
