### ISSUE TITLE
check_cassandra_* scripts don't seem to work with C* 2.1.x

### ISSUE THREAD

**Issue by thunderstumpges** [harisekhon/nagios-plugins#63]
We are upgrading to C* 2.1.8 and noticed the cassandra check scripts are not compatible. Any chances for an update in short order? I am not savvy in Perl, but could take a shot at hacking them to work with the latest version I guess.

**Comment by harisekhon** [comment]
@thunderstumpges 

I just downloaded 2.1.8 and ran and quick test and the plugins ran fine.

Can you please provide more details, run each plugin on the command line with ```-vvv``` in order to show the full output and paste it back here for review.

It's possible something is different in your setup that changes the output somehow and strict parsing fails it.

**Comment by thunderstumpges** [comment]
My Bad. Our Ops deployment didn't have the latest scripts. It appears the fix was made already (Nodetool.pm => $nodetool_status_header_regex)
Sorry for the false alarm.
