### ISSUE TITLE
checks having threads issue

### ISSUE THREAD

**Issue by shalstea** [HariSekhon/nagios-plugins#81]
I am trying to run some of the checks on RedHat el7 - perl5 (revision 5 version 16 subversion 3)
I am seeing the following error:
*CRITICAL: Can't locate object method "tid" via package "threads" at /usr/share/perl5/XSLoader.pm line 92.*
when I run it via:
*perl -T -Mthreads ./check_hadoop_datanodes.pl*
it works fine.  I am not a perl expert but someone at work recommended this and said you might need to add a line use threads;  Do you know what is going on / wrong ?  Thanks, Scott

**Comment by harisekhon** [comment]
I only recall seeing this issue crop up when running with http_proxy/https_proxy environment variable set.

I'm not sure if I should add use threads since it's use is official discouraged as it's not the lightweight mechanism many had hoped for. I will try to find some time to test this tomorrow, but I suspect this being caused by "optimization" by JSON::XS and that it might also subside if changing use JSON::XS to use JSON.

**Comment by shalstea** [comment]
I confirmed that.  We have both http_proxy and https_proxy set.  When I cleared these env variables the -Mthreads setting is not required.  It would obviously be preferred to not have to clear these env variables.

**Comment by harisekhon** [comment]
I added threads to the underlying utils library, try

```make update2```

This should resolve your issue.
