### ISSUE TITLE
Znode base '/' returns 'invalid base znode'

### ISSUE THREAD

**Issue by eborned** [HariSekhon/nagios-plugins#98]
I've upgraded to the newest version of the plugins. When trying to set my base Znode for SolrCloud, I get the following error:

invalid base znode (does not match regex critera): '/'

I'm calling one of the plugins as follows (hostnames are fake for this snippet, but real in my configuration)

./check_solrcloud_overseer_zookeeper.pl -H zk1.example.org,zk2.example.org,zk3.example.org --random-conn-order -b /

When I skip the -b parameter, it 'works'. But it then tries to find '/solr', which is not the base of my configuration. I need to use / as root.

**Comment by HariSekhon** [comment]
@eborned 

Thanks for reporting this - there was an old issue of not accepting znodes which were just / which was fixed in other zookeeper plugins but these ones were left using non-znode specific validation subroutines so didn't pick up the improvements.

I've updated them and added tests to cover this.

Please ```make update-no-recompile``` and try again - that should fix it for you.

Regards

Hari
