### ISSUE TITLE
Issue on check cassandra heap plugin : Exception 

### ISSUE THREAD

**Issue by floppy84** [HariSekhon/nagios-plugins#99]
hi,

I try to run ./check_cassandra_heap.pl on test env but i got CRITICAL: Exceptions             : 0
message.

this is the output in verbose mode ::

```
verbose mode on

check_cassandra_heap.pl version 0.2.1  =>  Hari Sekhon Utils version 1.18.1

nodetool:                 nodetool
host:                     cav-dev-esccorcsd-1
port:                     7199
user:                     cassandra
password:                 <omitted>
warning  upper:           80
critical upper:           90

setting timeout to 20 secs

fetching cluster node heap information
cmd: /usr/bin/nodetool --host '10.70.8.59' --port '7199' --username 'cassandra' --password '*******' info
output:

ID                     : 6cfd4702-61e1-4f97-8f70-fc890ceac924
Gossip active          : true
Thrift active          : true
Native Transport active: true
Load                   : 15.36 GB
Generation No          : 1464854575
Uptime (seconds)       : 2641
Heap Memory (MB)       : 333,17 / 912,00
Off Heap Memory (MB)   : 127,97
Data Center            : datacenter1
Rack                   : rack1
Exceptions             : 0
Key Cache              : entries 187, size 171,65 KB, capacity 45 MB, 21781 hits, 22059 requests, 0,987 recent hit rate, 14400 save period in seconds
Row Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, NaN recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 22 MB, 0 hits, 0 requests, NaN recent hit rate, 7200 save period in seconds
Token                  : (invoke with -T/--tokens to see all 256 tokens)

exitcode: 0

CRITICAL: Exceptions             : 0
```

regards

**Comment by HariSekhon** [comment]
@floppy84 

Thanks for raising this. I think this is a new field in output and there is a generic error catcher which is flagging it due to the exception keyword.

What version of Cassandra is this? I'll update the code and test against.

**Comment by floppy84** [comment]
@HariSekhon 

The version of cassandra that we use is : 2.2.3-1

thanks.

regards

**Comment by HariSekhon** [comment]
Ok the exceptions issue is not normally hit, it was because it fell through in not finding the heaps due to the comma instead of the dot separator. What locale are you using?

I've added a fix for that to accept commas as separator and convert, as well as a fix to ignore Exceptions in nodetool output since it's a normal field, albeit not one that is normally scanned until.

Given you are have commas instead of the usual dot separator you may encounter similar issues with some other plugins where they assume in regex ```\d+.\d+```, in which case please raise a ticket on an as needed basis and I'll do updates for those too.

Please ```make update-no-recompile``` and try again - it should work for you now.

Regards

Hari

**Comment by floppy84** [comment]
Yes it's work well right now !! thanks !!

**Comment by HariSekhon** [comment]
Thanks for confirming, closing this ticket.
